# Generated by Django 4.2.7 on 2023-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=20)),
                ('Photo', models.FileField(upload_to='')),
                ('Email', models.EmailField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('Local', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=7)),
            ],
        ),
    ]
